env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    CIRRUS_SHELL: bash
    token: ENCRYPTED[3b89b62e5529cc0abbf2406f62281df1cd72b664ec8477f77a47f16128413328c7d3dacc764260f8f61998581f388b24]
    token2: ENCRYPTED[a3d66934dc5635c72fd70e0a5a65a4c926c8ff6e96a555885eea9deef88f2e806b20b7370c7c417116e014665f3ab98b]

task:
    name: dump
    timeout_in: 2h
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g

    setup_script:
      - git clone https://github.com/XenStuff/phoenix_firmware_dumper phx
      - bash phx/setup.sh

    dump_script:
      - bash dump.sh
