env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    CIRRUS_SHELL: bash

task:
    name: dump
    timeout_in: 2h
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g

    setup_script:
      - git clone https://github.com/XenStuff/phoenix_firmware_dumper phx
      - echo "TG_TOKEN=${{ secrets.TG_TOKEN }}" > env/.tg_token
      - echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" > env/.github_token
      - echo "TG_CHAT=-1001563297164" > env/.tg_chat
      - echo "GH_ORG=XenStuff" > env/.github_orgname
      - bash phx/setup.sh

    dump_script:
      - bash dump.sh
